import { generateId, todayISO } from "@/utils/helpers.js";

import { StateManager } from "@/models/state.model.js";

export const PlanAutoLogService = {
  /**
   * Creates an automated log entry when a plan reaches completion.
   * Extracts all numeric objectives directly as metrics alongside general metrics.
   * @param {Object} plan - The completed plan object
   * @returns {Object|null} Created log entry or null if already logged
   */
  createAutoLogForPlan(plan) {
    if (!plan || !plan.id) return null;

    const currentState = StateManager.getState();
    const existingLogs = currentState.logs || [];

    const alreadyLogged = existingLogs.some(
      (log) =>
        String(log.planId) === String(plan.id) && log.isAutoGenerated === true,
    );

    if (alreadyLogged) return null;

    const objectives = Array.isArray(plan.objectives) ? plan.objectives : [];
    const metricsData = {};

    objectives
      .filter((obj) => obj.type === "numeric")
      .forEach((obj) => {
        const metricValue = Number(
          obj.targetValue ?? obj.target ?? obj.currentValue ?? obj.value ?? 0,
        );
        const metricUnit = obj.unit || "units";
        const metricName = obj.title || "Untitled Objective";

        metricsData[metricName] = {
          value: metricValue,
          unit: metricUnit,
        };
      });

    const totalObjectives = objectives.length;
    metricsData["Completed Objectives"] = {
      value: totalObjectives,
      unit: "items",
    };
    metricsData["Completion Progress"] = {
      value: 100,
      unit: "%",
    };

    const newAutoLog = {
      id: generateId(),
      planId: plan.id,
      title: `Automated Completion: ${plan.title || "Untitled Plan"}`,
      description: `All ${totalObjectives} objectives were successfully completed. Plan state marked as COMPLETED.`,
      date: todayISO(),
      energy: 5,
      mood: "excellent",
      isAutoGenerated: true,
      metrics: metricsData,
      createdAt: todayISO(),
    };

    const updatedLogs = [newAutoLog, ...existingLogs];

    StateManager.save({ logs: updatedLogs });

    return newAutoLog;
  },
};
